name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Compile Definitions
        run: docker run --rm -v "$PWD":/work -w /work p4lang/p4c sh -c 'set -e; find . -name "*.p4" | while read program; do echo "compiling $program"; p4c-bm2-ss "$program" -o "/tmp/program.json"; done'


